#!/bin/bash -e

mode=$([[ -f /etc/debian_version ]]  &&  printf "debian" || printf "yocto" )
mode=debian
GRUB_CFG=/usr/share/compulab/grub-bootconf-${mode}

do_grub_cfg_debian() {
ROOT_UUID=$(grub-probe --device ${GRUB_DEVICE} --target=fs_uuid)
sed "s/ROOT_UUID/$ROOT_UUID/g" ${GRUB_CFG}
}

do_grub_cfg_yocto() {
DISTRO=$(sed 's/\\.*$//g' /etc/issue)
command -v ischroot && rc=$? || rc=$?

if [[ ${rc} -eq 0 ]];then
ischroot && rc=$? || rc=$?
fi

if [[ ${rc} -eq 0 ]];then
	sed "s|DISTRO|${DISTRO}|g" ${GRUB_CFG}
else
	eval $(blkid $(findmnt / -o SOURCE -n) | awk -F":" '($0=$2)')
	sed "s/\(^UUID\)=.*/\1=${UUID}/g;s/\(^PARTUUID\).*$/\1=${PARTUUID}/g;s|DISTRO|${DISTRO}|g" ${GRUB_CFG}
fi
}

[[ ! -f ${GRUB_CFG} ]] || do_grub_cfg_${mode}
