#!/bin/bash -e

GRUB_CFG=/usr/share/compulab/grub-bootconf

do_grub_cfg() {
DISTRO=$(sed 's/\\.*$//g' /etc/issue)
ischroot && rc=$? || rc=$?

if [[ ${rc} -eq 0 ]];then
	sed "s|DISTRO|${DISTRO}|g" ${GRUB_CFG}
else
	eval $(blkid $(findmnt / -o SOURCE -n) | awk -F":" '($0=$2)')
	sed "s/\(^UUID\)=.*/\1=${UUID}/g;s/\(^PARTUUID\).*$/\1=${PARTUUID}/g;s|DISTRO|${DISTRO}|g" ${GRUB_CFG}
fi
}

[[ ! -f ${GRUB_CFG} ]] || do_grub_cfg
